package com.SpringBootRESTAPIs.store.mappers;

import com.SpringBootRESTAPIs.store.dtos.RegisterUserRequest;
import com.SpringBootRESTAPIs.store.dtos.UpdateUserRequest;
import com.SpringBootRESTAPIs.store.dtos.UserDto;
import com.SpringBootRESTAPIs.store.entities.User;
import org.mapstruct.Mapper;
import org.mapstruct.MappingTarget;
// implementation of this interface will be generated by the mapstruct library at compile time. we need to add the mapstruct dependency to our project to use this library. we also need to add the annotation processor dependency to our project to generate the implementation of this interface at compile time. we can use the generated implementation of this interface in our service layer to map between user and userdto and between registeruserrequest and user and to update the user entity with the fields from the updateuserrequest.
@Mapper(componentModel = "spring")
public interface UserMapper {
    UserDto toDto(User user); // this will map a user to a userdto using the mapstruct library. the name of the method is not important just the input type and output type are important.
    User toEntity(RegisterUserRequest request); // this will map a registeruserrequest to a user using the mapstruct library. the name of the method is not important just the input type and output type are important. we need this method to create a user from the registeruserrequest received from the client.
    void update(UpdateUserRequest request, @MappingTarget User user); // this will update the user entity annotated with @MappingTarget with the fields from the updateuserrequest. we need this method to update the user entity with the fields received from the client in the updateuserrequest.

}
